# Generated by Django 4.1.6 on 2023-02-06 18:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseModel',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Car_type',
            fields=[
                ('Car_type_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Car_type', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('car_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('car_name', models.CharField(max_length=200)),
                ('is_used', models.BooleanField()),
                ('car_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_type', to='home.car_type')),
            ],
        ),
        migrations.CreateModel(
            name='shipment',
            fields=[
                ('shipment_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('shipment_name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Path', models.TextField()),
                ('createdate', models.DateField(auto_now_add=True)),
                ('transport_done', models.BooleanField()),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Car', to='home.cars')),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipment', to='home.shipment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transforms', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
