# Generated by Django 4.1.6 on 2023-02-07 07:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_delete_basemodel_rename_car_type_id_car_type_uid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shipment',
            old_name='shipment_id',
            new_name='uid',
        ),
        migrations.AddField(
            model_name='shipment',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shipment',
            name='updated_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
