# Generated by Django 4.1.6 on 2023-02-07 08:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_shipment_id_shipment_uid_shipment_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cars',
            old_name='car_id',
            new_name='uid',
        ),
        migrations.AddField(
            model_name='cars',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cars',
            name='updated_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
