# Generated by Django 4.1.6 on 2023-02-07 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_rename_car_id_cars_uid_cars_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transport',
            name='is_done',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
